//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEONow.Context.EntityContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignMenuHeader
    {
        public int AssignMenuHeader_PK { get; set; }
        public Nullable<System.DateTime> Cre_Date { get; set; }
        public string Cre_User { get; set; }
        public Nullable<System.DateTime> Mod_Date { get; set; }
        public string Mod_User { get; set; }
    
        public virtual MenuHeaderConfiguration MenuHeaderConfiguration { get; set; }
        public virtual MenuConfiguration MenuConfiguration { get; set; }
    }
}
