//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEONow.Context.EntityContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailableLaborMarketData
    {
        public int AvailableLaborMarketDataId { get; set; }
        public Nullable<int> MaleValue { get; set; }
        public Nullable<int> FemaleValue { get; set; }
        public int CreateUserId { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
    
        public virtual AvailableLaborMarketFileVersion AvailableLaborMarketFileVersion { get; set; }
        public virtual EEOJobCategory EEOJobCategory { get; set; }
        public virtual Race Race { get; set; }
    }
}
