//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEONow.Context.EntityContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailAuthenticateLog
    {
        public int EmailLogId { get; set; }
        public string AuthenticateCode { get; set; }
        public bool Active { get; set; }
        public System.DateTime EmailSentTime { get; set; }
        public int CreateUserId { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
    
        public virtual User User { get; set; }
        public virtual LoginDeviceInfo LoginDeviceInfo { get; set; }
    }
}
