//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEONow.Context.EntityContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.EmployeeLevels = new HashSet<EmployeeLevel>();
        }
    
        public int EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public bool Filled { get; set; }
        public Nullable<System.DateTime> VacancyDate { get; set; }
        public string PositionNumber { get; set; }
        public string SupervisorPositionNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public bool SupervisorFlag { get; set; }
        public Nullable<decimal> EEORaceIndex { get; set; }
        public Nullable<decimal> EEOGenderIndex { get; set; }
        public Nullable<int> SpanOfControl { get; set; }
        public string NationalOrigin { get; set; }
        public int Age { get; set; }
        public string PositionTitle { get; set; }
        public string ProgramOfficeName { get; set; }
        public Nullable<bool> OPSPosition { get; set; }
        public decimal Salary { get; set; }
        public Nullable<decimal> LastPerformanceRatingValue { get; set; }
        public Nullable<System.DateTime> PositionDateOfHire { get; set; }
        public Nullable<System.DateTime> AgencyDateOfHire { get; set; }
        public int StateCumulativeMonthsOfService { get; set; }
        public int UserID { get; set; }
        public string WorkAddress { get; set; }
        public string WorkCity { get; set; }
        public string WorkZipCode { get; set; }
        public int CreateUserId { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string RegionName { get; set; }
    
        public virtual AgencyYearsOfService AgencyYearsOfService { get; set; }
        public virtual AgeRange AgeRange { get; set; }
        public virtual County County { get; set; }
        public virtual EEOJobCategory EEOJobCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeLevel> EmployeeLevels { get; set; }
        public virtual FileSubmission FileSubmission { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual LastPerformanceRating LastPerformanceRating { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual PositionYearsOfService PositionYearsOfService { get; set; }
        public virtual Race Race { get; set; }
        public virtual SalaryRange SalaryRange { get; set; }
        public virtual State State { get; set; }
        public virtual VacancyRange VacancyRange { get; set; }
    }
}
