//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEONow.Context.EntityContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileSubmission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FileSubmission()
        {
            this.Employees = new HashSet<Employee>();
            this.FileSubmissionRecords = new HashSet<FileSubmissionRecord>();
            this.GenerateCSVs = new HashSet<GenerateCSV>();
        }
    
        public int FileSubmissionId { get; set; }
        public string OriginalFileName { get; set; }
        public string NewFileName { get; set; }
        public Nullable<System.DateTime> SubmissionDateTime { get; set; }
        public int FileVersionNumber { get; set; }
        public int CreateUserId { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
    
        public virtual AvailableLaborMarketFileVersion AvailableLaborMarketFileVersion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileSubmissionRecord> FileSubmissionRecords { get; set; }
        public virtual FileSubmissionStatu FileSubmissionStatu { get; set; }
        public virtual Organization Organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GenerateCSV> GenerateCSVs { get; set; }
    }
}
