//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEONow.Context.EntityContext
{
    using System;
    
    public partial class getCSVGraphData_Result1
    {
        public string position { get; set; }
        public string parent { get; set; }
        public Nullable<int> level { get; set; }
        public string first { get; set; }
        public string middle { get; set; }
        public string last { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string gender { get; set; }
        public string race { get; set; }
        public int age { get; set; }
        public string positionTitle { get; set; }
        public string programOffice { get; set; }
        public string salary { get; set; }
        public string eeo4Code { get; set; }
        public string lastPerformanceRating { get; set; }
        public string agency { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string county { get; set; }
        public string state { get; set; }
        public string zipCode { get; set; }
        public Nullable<int> supervisorFlag { get; set; }
        public string staffHeadCount { get; set; }
        public string NumberFTEPositions { get; set; }
        public string NumberOPSPositions { get; set; }
        public string NumberFTEVacantPositions { get; set; }
        public string NumberOPSVacantPositions { get; set; }
        public string NumberFTEFilledPositions { get; set; }
        public string NumberOPSFilledPositions { get; set; }
        public Nullable<int> spanOfControl { get; set; }
        public string supervisorStaffRatio { get; set; }
        public string TotalMinoritySupervisors { get; set; }
        public string TotalWomenSupervisors { get; set; }
        public string PercentMinoritySupervisors { get; set; }
        public string PercentWomenSupervisors { get; set; }
        public string TotalSupervisors { get; set; }
        public Nullable<int> levelsUP { get; set; }
        public Nullable<int> levelsDown { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> yearsFRS { get; set; }
        public Nullable<decimal> yearsAgency { get; set; }
        public Nullable<decimal> yearsCurrentPosition { get; set; }
        public int raceid { get; set; }
        public int tysid { get; set; }
        public int eeoid { get; set; }
        public int srid { get; set; }
        public int pspid { get; set; }
        public int arid { get; set; }
        public int lprid { get; set; }
        public decimal eeoratingracevalue { get; set; }
        public decimal eeoratinggendervalue { get; set; }
        public string NationalOrigin { get; set; }
        public Nullable<bool> OPSPosition { get; set; }
        public int StateCumulativeMonthsOfService { get; set; }
        public string PositionDateOfHire { get; set; }
        public string AgencyDateOfHire { get; set; }
        public int UserID { get; set; }
        public Nullable<int> filled { get; set; }
        public Nullable<int> vacant { get; set; }
        public Nullable<int> genderFemale { get; set; }
        public Nullable<int> genderMale { get; set; }
        public Nullable<int> EEOC1 { get; set; }
        public Nullable<int> EEOC2 { get; set; }
        public Nullable<int> EEOC3 { get; set; }
        public Nullable<int> EEOC4 { get; set; }
        public Nullable<int> EEOC5 { get; set; }
        public Nullable<int> EEOC6 { get; set; }
        public Nullable<int> EEOC7 { get; set; }
        public Nullable<int> EEOC8 { get; set; }
        public Nullable<int> R1 { get; set; }
        public Nullable<int> R2 { get; set; }
        public Nullable<int> R3 { get; set; }
        public Nullable<int> R4 { get; set; }
        public Nullable<int> R5 { get; set; }
        public Nullable<int> R6 { get; set; }
        public Nullable<int> R7 { get; set; }
        public Nullable<int> SR1 { get; set; }
        public Nullable<int> SR2 { get; set; }
        public Nullable<int> SR3 { get; set; }
        public Nullable<int> SR4 { get; set; }
        public Nullable<int> SR5 { get; set; }
        public Nullable<int> SR6 { get; set; }
        public Nullable<int> SR7 { get; set; }
        public Nullable<int> SR8 { get; set; }
        public Nullable<int> SR9 { get; set; }
        public Nullable<int> AR1 { get; set; }
        public Nullable<int> AR2 { get; set; }
        public Nullable<int> AR3 { get; set; }
        public Nullable<int> AR4 { get; set; }
        public Nullable<int> AR5 { get; set; }
        public Nullable<int> AR6 { get; set; }
        public Nullable<int> AR7 { get; set; }
        public Nullable<int> AR8 { get; set; }
        public Nullable<int> PYOS1 { get; set; }
        public Nullable<int> PYOS2 { get; set; }
        public Nullable<int> PYOS3 { get; set; }
        public Nullable<int> PYOS4 { get; set; }
        public Nullable<int> PYOS5 { get; set; }
        public Nullable<int> PYOS6 { get; set; }
        public Nullable<int> PYOS7 { get; set; }
        public Nullable<int> PYOS8 { get; set; }
        public Nullable<int> AYOS1 { get; set; }
        public Nullable<int> AYOS2 { get; set; }
        public Nullable<int> AYOS3 { get; set; }
        public Nullable<int> AYOS4 { get; set; }
        public Nullable<int> AYOS5 { get; set; }
        public Nullable<int> AYOS6 { get; set; }
        public Nullable<int> AYOS7 { get; set; }
        public Nullable<int> AYOS8 { get; set; }
        public Nullable<int> LPR1 { get; set; }
        public Nullable<int> LPR2 { get; set; }
        public Nullable<int> LPR3 { get; set; }
        public Nullable<int> LPR4 { get; set; }
        public Nullable<int> LPR5 { get; set; }
        public string EEOR1 { get; set; }
        public string EEOR2 { get; set; }
        public string EEOR3 { get; set; }
    }
}
