//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEONow.Context.EntityContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginDeviceInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoginDeviceInfo()
        {
            this.EmailAuthenticateLogs = new HashSet<EmailAuthenticateLog>();
        }
    
        public int LoginDeviceInfoId { get; set; }
        public string DeviceAccessInfo { get; set; }
        public string IpAddress { get; set; }
        public string MacAdresss { get; set; }
        public string RandomKey { get; set; }
        public System.DateTime LoginDateTime { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public int NoOfTimeLogin { get; set; }
        public bool IsMobile { get; set; }
        public bool IsVerified { get; set; }
        public int CreateUserId { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailAuthenticateLog> EmailAuthenticateLogs { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual User User { get; set; }
    }
}
