//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEONow.Context.EntityContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuHeaderConfiguration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuHeaderConfiguration()
        {
            this.AssignMenuHeaders = new HashSet<AssignMenuHeader>();
        }
    
        public int MenuHeaderID_PK { get; set; }
        public string MenuKey { get; set; }
        public Nullable<bool> IsHeader { get; set; }
        public int SortOrder { get; set; }
        public string Name { get; set; }
        public string MenuController { get; set; }
        public string MenuAction { get; set; }
        public string MenuIcon { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Cre_Date { get; set; }
        public string Cre_User { get; set; }
        public Nullable<System.DateTime> Mod_Date { get; set; }
        public string Mod_User { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignMenuHeader> AssignMenuHeaders { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
