//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEONow.Context.EntityContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class USCensus_ALLData
    {
        public int USCensusDataID { get; set; }
        public string StateResidenceCode { get; set; }
        public string PUMAResidenceCode { get; set; }
        public string StateWorksiteCode { get; set; }
        public string PUMAWorksiteCode { get; set; }
        public int RaceID { get; set; }
        public int Gender { get; set; }
        public int PWGTPCount { get; set; }
        public string OCCPJobCode { get; set; }
        public string ESRCode { get; set; }
        public int AGEPCode { get; set; }
        public string HISPCode { get; set; }
    
        public virtual USCensus_DataVersion USCensus_DataVersion { get; set; }
    }
}
