//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEONow.Context.EntityContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class USCensus_Occupations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USCensus_Occupations()
        {
            this.USCensus_Occupations_EEOJobClasificationCategories = new HashSet<USCensus_Occupations_EEOJobClasificationCategories>();
        }
    
        public int OccupationID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
    
        public virtual USCensus_BoardingOccupationGroups USCensus_BoardingOccupationGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USCensus_Occupations_EEOJobClasificationCategories> USCensus_Occupations_EEOJobClasificationCategories { get; set; }
    }
}
