//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEONow.Context.EntityContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class USCensus_Occupations_EEOJobClasificationCategories
    {
        public int OccupationID { get; set; }
        public int EEOJobClasificationCategoryID { get; set; }
        public bool Active { get; set; }
    
        public virtual USCensus_EEOJobClasificationCategories USCensus_EEOJobClasificationCategories { get; set; }
        public virtual USCensus_Occupations USCensus_Occupations { get; set; }
    }
}
