//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wempe
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int customerNumber { get; set; }
        public Nullable<System.DateTime> entryDate { get; set; }
        public string title { get; set; }
        public string firstName { get; set; }
        public string middleInitial { get; set; }
        public string lastName { get; set; }
        public string asstTitle { get; set; }
        public string asstFirstName { get; set; }
        public string asstMiddleInitial { get; set; }
        public string asstLastName { get; set; }
        public string priCompany { get; set; }
        public string priAddressLine1 { get; set; }
        public string priAddressLine2 { get; set; }
        public string priCity { get; set; }
        public string priState { get; set; }
        public string priZipCode { get; set; }
        public string priZipCodePlusFour { get; set; }
        public string priCountry { get; set; }
        public string priTelephoneSegment1 { get; set; }
        public string priTelephoneSegment2 { get; set; }
        public string priTelephoneSegment3 { get; set; }
        public string priTelephoneExtension { get; set; }
        public string priCellphoneSegment1 { get; set; }
        public string priCellphoneSegment2 { get; set; }
        public string priCellphoneSegment3 { get; set; }
        public string priFaxSegment1 { get; set; }
        public string priFaxSegment2 { get; set; }
        public string priFaxSegment3 { get; set; }
        public string priEMailAddress { get; set; }
        public string secCompany { get; set; }
        public string secAddressLine1 { get; set; }
        public string secAddressLine2 { get; set; }
        public string secCity { get; set; }
        public string secState { get; set; }
        public string secZipCode { get; set; }
        public string secZipCodePlusFour { get; set; }
        public string secCountry { get; set; }
        public string secTelephoneSegment1 { get; set; }
        public string secTelephoneSegment2 { get; set; }
        public string secTelephoneSegment3 { get; set; }
        public string secTelephoneExtension { get; set; }
        public string secCellphoneSegment1 { get; set; }
        public string secCellphoneSegment2 { get; set; }
        public string secCellphoneSegment3 { get; set; }
        public string secFaxSegment1 { get; set; }
        public string secFaxSegment2 { get; set; }
        public string secFaxSegment3 { get; set; }
        public string secEMailAddress { get; set; }
        public string priCreditCardSegment1 { get; set; }
        public string priCreditCardSegment2 { get; set; }
        public string priCreditCardSegment3 { get; set; }
        public string priCreditCardSegment4 { get; set; }
        public string priCreditCardExpMonth { get; set; }
        public string priCreditCardExpYear { get; set; }
        public string secCreditCardSegment1 { get; set; }
        public string secCreditCardSegment2 { get; set; }
        public string secCreditCardSegment3 { get; set; }
        public string secCreditCardSegment4 { get; set; }
        public string secCreditCardExpMonth { get; set; }
        public string secCreditCardExpYear { get; set; }
        public string contactPreference { get; set; }
        public string customerType { get; set; }
        public string notes { get; set; }
    }
}
