//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wempe
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCustomer
    {
        public long customerNumber { get; set; }
        public string FullName { get; set; }
        public string PrimaryAddress { get; set; }
        public string City { get; set; }
        public string PrimaryPhone { get; set; }
        public string priEMailAddress { get; set; }
        public string CountryName { get; set; }
        public string stateName { get; set; }
        public Nullable<long> OwnerID { get; set; }
    }
}
