//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wempe
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbWempeEntities : DbContext
    {
        public dbWempeEntities()
            : base("name=dbWempeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<wmpAppraiserMaster> wmpAppraiserMasters { get; set; }
        public DbSet<wmpAppraiserTitle> wmpAppraiserTitles { get; set; }
        public DbSet<wmpBackConditionMaster> wmpBackConditionMasters { get; set; }
        public DbSet<wmpBandCondition> wmpBandConditions { get; set; }
        public DbSet<wmpBandTypeMaster> wmpBandTypeMasters { get; set; }
        public DbSet<wmpBandTypeMaster1> wmpBandTypeMaster1 { get; set; }
        public DbSet<wmpBezelConditionMaster> wmpBezelConditionMasters { get; set; }
        public DbSet<wmpBoxIncludedMaster> wmpBoxIncludedMasters { get; set; }
        public DbSet<wmpBrandMaster> wmpBrandMasters { get; set; }
        public DbSet<wmpBuckleConditionMaster> wmpBuckleConditionMasters { get; set; }
        public DbSet<wmpBuckleType> wmpBuckleTypes { get; set; }
        public DbSet<wmpCarrier> wmpCarriers { get; set; }
        public DbSet<wmpCaseCondition> wmpCaseConditions { get; set; }
        public DbSet<wmpCaseType> wmpCaseTypes { get; set; }
        public DbSet<wmpCategoryMaster> wmpCategoryMasters { get; set; }
        public DbSet<wmpCompanyMaster> wmpCompanyMasters { get; set; }
        public DbSet<wmpCompanyPackage> wmpCompanyPackages { get; set; }
        public DbSet<wmpContactPreference> wmpContactPreferences { get; set; }
        public DbSet<wmpCountry> wmpCountries { get; set; }
        public DbSet<wmpCounty> wmpCounties { get; set; }
        public DbSet<wmpCrystalCondition> wmpCrystalConditions { get; set; }
        public DbSet<wmpCustomer> wmpCustomers { get; set; }
        public DbSet<wmpCustomerType> wmpCustomerTypes { get; set; }
        public DbSet<wmpDestinationType> wmpDestinationTypes { get; set; }
        public DbSet<wmpDialCondition> wmpDialConditions { get; set; }
        public DbSet<wmpDialType> wmpDialTypes { get; set; }
        public DbSet<wmpDocument> wmpDocuments { get; set; }
        public DbSet<wmpEmployee> wmpEmployees { get; set; }
        public DbSet<wmpEngravingCapitalization> wmpEngravingCapitalizations { get; set; }
        public DbSet<wmpEngravingFont> wmpEngravingFonts { get; set; }
        public DbSet<wmpErrorLog> wmpErrorLogs { get; set; }
        public DbSet<wmpFileAttachment> wmpFileAttachments { get; set; }
        public DbSet<wmpIDSecurity> wmpIDSecurities { get; set; }
        public DbSet<wmpImportStatu> wmpImportStatus { get; set; }
        public DbSet<wmpItem> wmpItems { get; set; }
        public DbSet<wmpLastRecordSet> wmpLastRecordSets { get; set; }
        public DbSet<wmpLugsCondition> wmpLugsConditions { get; set; }
        public DbSet<wmpMailBox> wmpMailBoxes { get; set; }
        public DbSet<wmpMailBoxEmailAddress> wmpMailBoxEmailAddresses { get; set; }
        public DbSet<wmpMenuMaster> wmpMenuMasters { get; set; }
        public DbSet<wmpMovementType> wmpMovementTypes { get; set; }
        public DbSet<wmpMVCAuthenticationRight> wmpMVCAuthenticationRights { get; set; }
        public DbSet<wmpPrintSetting> wmpPrintSettings { get; set; }
        public DbSet<wmpPurchaseLocation> wmpPurchaseLocations { get; set; }
        public DbSet<wmpRecentRepair> wmpRecentRepairs { get; set; }
        public DbSet<wmpRepair> wmpRepairs { get; set; }
        public DbSet<wmpRepairLog> wmpRepairLogs { get; set; }
        public DbSet<wmpRepairSampleTask> wmpRepairSampleTasks { get; set; }
        public DbSet<wmpRepairType> wmpRepairTypes { get; set; }
        public DbSet<wmpResetPassword> wmpResetPasswords { get; set; }
        public DbSet<wmpRoleMaster> wmpRoleMasters { get; set; }
        public DbSet<wmpRoleRelationship> wmpRoleRelationships { get; set; }
        public DbSet<wmpSampleCity> wmpSampleCities { get; set; }
        public DbSet<wmpShipping> wmpShippings { get; set; }
        public DbSet<wmpShippingType> wmpShippingTypes { get; set; }
        public DbSet<wmpState> wmpStates { get; set; }
        public DbSet<wmpStatu> wmpStatus { get; set; }
        public DbSet<wmpStolenRepair> wmpStolenRepairs { get; set; }
        public DbSet<wmpStoreInformation> wmpStoreInformations { get; set; }
        public DbSet<wmpStrapAccessory> wmpStrapAccessories { get; set; }
        public DbSet<wmpStrapColor> wmpStrapColors { get; set; }
        public DbSet<wmpStrapLusterType> wmpStrapLusterTypes { get; set; }
        public DbSet<wmpStrapStitchType> wmpStrapStitchTypes { get; set; }
        public DbSet<wmpStrapTextureType> wmpStrapTextureTypes { get; set; }
        public DbSet<wmpStrapThicknessType> wmpStrapThicknessTypes { get; set; }
        public DbSet<wmpStyle> wmpStyles { get; set; }
        public DbSet<wmpSuggestion> wmpSuggestions { get; set; }
        public DbSet<wmpSupplier> wmpSuppliers { get; set; }
        public DbSet<wmpSystem> wmpSystems { get; set; }
        public DbSet<wmpTaxRate> wmpTaxRates { get; set; }
        public DbSet<wmpTitle> wmpTitles { get; set; }
        public DbSet<wmpUserMaster> wmpUserMasters { get; set; }
        public DbSet<wmpUserTrack> wmpUserTracks { get; set; }
        public DbSet<wmpWarrantyDocument> wmpWarrantyDocuments { get; set; }
        public DbSet<wmpWarrantyTypeMaster> wmpWarrantyTypeMasters { get; set; }
        public DbSet<wmpWebsitePage> wmpWebsitePages { get; set; }
        public DbSet<wmpWebsitePagesLinking> wmpWebsitePagesLinkings { get; set; }
        public DbSet<wmpZipCode> wmpZipCodes { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<TestEntry> TestEntries { get; set; }
        public DbSet<wmpBoxIncluded> wmpBoxIncludeds { get; set; }
        public DbSet<wmpStrapLength> wmpStrapLengths { get; set; }
        public DbSet<wmpstrapMaterialType> wmpstrapMaterialTypes { get; set; }
        public DbSet<vwCustomer> vwCustomers { get; set; }
        public DbSet<vwRepair> vwRepairs { get; set; }
        public DbSet<wmpWebsiteTheme> wmpWebsiteThemes { get; set; }
        public DbSet<wmpRepairStatusLog> wmpRepairStatusLogs { get; set; }
    }
}
