//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wempe
{
    using System;
    using System.Collections.Generic;
    
    public partial class wmpCategoryMaster
    {
        public long CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string CategoryUrl { get; set; }
        public string CategoryImage { get; set; }
        public Nullable<int> CategoryIndex { get; set; }
        public string metaTitel { get; set; }
        public string metakeywords { get; set; }
        public string metaDescription { get; set; }
        public Nullable<long> parentID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<long> UpdateBy { get; set; }
        public Nullable<long> OwnerID { get; set; }
    }
}
