//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wempe
{
    using System;
    using System.Collections.Generic;
    
    public partial class wmpCompanyPackage
    {
        public long Id { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public string PackageStartDate { get; set; }
        public string PackageRenewalDate { get; set; }
        public Nullable<long> UserLimit { get; set; }
        public string PackagePeriod { get; set; }
        public string Payment { get; set; }
        public string PaymentMode { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> OwnerId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
