//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wempe
{
    using System;
    using System.Collections.Generic;
    
    public partial class wmpCustomer
    {
        public long customerNumber { get; set; }
        public Nullable<System.DateTime> entryDate { get; set; }
        public string title { get; set; }
        public string firstName { get; set; }
        public string middleInitial { get; set; }
        public string lastName { get; set; }
        public string asstTitle { get; set; }
        public string asstFirstName { get; set; }
        public string asstMiddleInitial { get; set; }
        public string asstLastName { get; set; }
        public string asstRelation { get; set; }
        public string priCompany { get; set; }
        public string priAddressLine1 { get; set; }
        public string priAddressLine2 { get; set; }
        public string priCity { get; set; }
        public Nullable<long> priState { get; set; }
        public string priZipCode { get; set; }
        public string priZipCodePlusFour { get; set; }
        public Nullable<long> priCountry { get; set; }
        public string priTelephoneSegment1 { get; set; }
        public string priTelephoneSegment2 { get; set; }
        public string priTelephoneSegment3 { get; set; }
        public string priTelephoneExtension { get; set; }
        public string priCellphoneSegment1 { get; set; }
        public string priCellphoneSegment2 { get; set; }
        public string priCellphoneSegment3 { get; set; }
        public string priFaxSegment1 { get; set; }
        public string priFaxSegment2 { get; set; }
        public string priFaxSegment3 { get; set; }
        public string priEMailAddress { get; set; }
        public string secCompany { get; set; }
        public string secAddressLine1 { get; set; }
        public string secAddressLine2 { get; set; }
        public string secCity { get; set; }
        public Nullable<long> secState { get; set; }
        public string secZipCode { get; set; }
        public string secZipCodePlusFour { get; set; }
        public Nullable<long> secCountry { get; set; }
        public string secTelephoneSegment1 { get; set; }
        public string secTelephoneSegment2 { get; set; }
        public string secTelephoneSegment3 { get; set; }
        public string secTelephoneExtension { get; set; }
        public string secHomephoneSegment1 { get; set; }
        public string secHomephoneSegment2 { get; set; }
        public string secHomephoneSegment3 { get; set; }
        public string secAssistanatSegment1 { get; set; }
        public string secAssistanatSegment2 { get; set; }
        public string secAssistanatSegment3 { get; set; }
        public string secAssistanatExtension { get; set; }
        public string secCellphoneSegment1 { get; set; }
        public string secCellphoneSegment2 { get; set; }
        public string secCellphoneSegment3 { get; set; }
        public string secFaxSegment1 { get; set; }
        public string secFaxSegment2 { get; set; }
        public string secFaxSegment3 { get; set; }
        public string secEMailAddress { get; set; }
        public string secEmailAddress2 { get; set; }
        public string priCreditCardSegment1 { get; set; }
        public string priCreditCardSegment2 { get; set; }
        public string priCreditCardSegment3 { get; set; }
        public string priCreditCardSegment4 { get; set; }
        public string priCreditCardExpMonth { get; set; }
        public string priCreditCardExpYear { get; set; }
        public string priCreditCardSecurity { get; set; }
        public string secCreditCardSegment1 { get; set; }
        public string secCreditCardSegment2 { get; set; }
        public string secCreditCardSegment3 { get; set; }
        public string secCreditCardSegment4 { get; set; }
        public string secCreditCardExpMonth { get; set; }
        public string secCreditCardExpYear { get; set; }
        public string secCreditCardSecurity { get; set; }
        public Nullable<long> contactPreference { get; set; }
        public Nullable<long> customerType { get; set; }
        public string notes { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<long> UpdateBy { get; set; }
        public Nullable<long> OwnerID { get; set; }
        public string priHomephoneSegment1 { get; set; }
        public string priHomephoneSegment2 { get; set; }
        public string priHomephoneSegment3 { get; set; }
        public string priAssistanatSegment1 { get; set; }
        public string priAssistanatSegment2 { get; set; }
        public string priAssistanatSegment3 { get; set; }
        public string priAssistanatExtension { get; set; }
        public string priEMailAddress2 { get; set; }
        public string thirdCompany { get; set; }
        public string thirdAddressLine1 { get; set; }
        public string thirdAddressLine2 { get; set; }
        public string thirdCity { get; set; }
        public string thirdState { get; set; }
        public string thirdZipCode { get; set; }
        public string thirdZipCodePlusFour { get; set; }
        public string thirdCountry { get; set; }
        public string thirdTelephoneSegment1 { get; set; }
        public string thirdTelephoneSegment2 { get; set; }
        public string thirdTelephoneSegment3 { get; set; }
        public string thirdTelephoneExtension { get; set; }
        public string thirdHomephoneSegment1 { get; set; }
        public string thirdHomephoneSegment2 { get; set; }
        public string thirdHomephoneSegment3 { get; set; }
        public string thirdAssistanatSegment1 { get; set; }
        public string thirdAssistanatSegment2 { get; set; }
        public string thirdAssistanatSegment3 { get; set; }
        public string thirdAssistanatExtension { get; set; }
        public string thirdCellphoneSegment1 { get; set; }
        public string thirdCellphoneSegment2 { get; set; }
        public string thirdCellphoneSegment3 { get; set; }
        public string thirdFaxSegment1 { get; set; }
        public string thirdFaxSegment2 { get; set; }
        public string thirdFaxSegment3 { get; set; }
        public string thirdEMailAddress { get; set; }
        public string thirdEMailAddress2 { get; set; }
        public string thirdCreditCardSegment1 { get; set; }
        public string thirdCreditCardSegment2 { get; set; }
        public string thirdCreditCardSegment3 { get; set; }
        public string thirdCreditCardSegment4 { get; set; }
        public string thirdCreditCardExpMonth { get; set; }
        public string thirdCreditCardExpYear { get; set; }
        public string thirdCreditCardSecurity { get; set; }
        public string SpouseRelation { get; set; }
        public string SpouseTitle { get; set; }
        public string SpousefirstName { get; set; }
        public string SpousemiddleInitial { get; set; }
        public string SpouselastName { get; set; }
        public string priHomePhoneExtension { get; set; }
        public string secHomePhoneExtension { get; set; }
        public string thirdHomePhoneExtension { get; set; }
        public string ShippingToServiceCenterValue { get; set; }
        public string ShippingToServiceCenterDecline { get; set; }
        public string ShippingToServiceCenterPrice { get; set; }
        public string ShippingToEuropeValue { get; set; }
        public string ShippingToEuropeDecline { get; set; }
        public string ShippingToEuropePrice { get; set; }
        public string EstimateFeeValue { get; set; }
        public string EstimateFeeDecline { get; set; }
        public string EstimateFeePrice { get; set; }
        public string ServiceMinimumChargeValue { get; set; }
        public string ServiceMinimumChargeDecline { get; set; }
        public string ServiceMinimumChargePrice { get; set; }
        public string Overhaul { get; set; }
        public string OptialWorkPartialRepairValue1 { get; set; }
        public string OptialWorkPartialRepairPrice1 { get; set; }
        public string OptialWorkPartialRepairValue2 { get; set; }
        public string OptialWorkPartialRepairPrice2 { get; set; }
        public string OptialWorkPartialRepairValue3 { get; set; }
        public string OptialWorkPartialRepairPrice3 { get; set; }
        public string OptialWorkPartialRepairValue4 { get; set; }
        public string OptialWorkPartialRepairPrice4 { get; set; }
        public string OptialWorkPartialRepairValue5 { get; set; }
        public string OptialWorkPartialRepairPrice5 { get; set; }
        public string OptialWorkPartialRepairValue6 { get; set; }
        public string OptialWorkPartialRepairPrice6 { get; set; }
        public string RepairComment { get; set; }
        public string SubTotal { get; set; }
        public string Shipping { get; set; }
        public string Tax { get; set; }
        public string Total { get; set; }
        public string priCountryCode { get; set; }
        public string AlternateCountryCode { get; set; }
        public string ThirdCountryCode { get; set; }
    }
}
