//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wempe
{
    using System;
    using System.Collections.Generic;
    
    public partial class wmpLastRecordSet
    {
        public int Id { get; set; }
        public Nullable<long> CustomerNumber { get; set; }
        public Nullable<long> RepairNumber { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> OwnderId { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
    }
}
