//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wempe
{
    using System;
    using System.Collections.Generic;
    
    public partial class wmpMailBoxEmailAddress
    {
        public long Id { get; set; }
        public string MailAddress { get; set; }
        public string DisplayName { get; set; }
        public Nullable<bool> HasValidMailAddress { get; set; }
        public Nullable<long> MailRelId { get; set; }
        public string AddressType { get; set; }
    }
}
