//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wempe
{
    using System;
    using System.Collections.Generic;
    
    public partial class wmpMenuMaster
    {
        public int MenuID { get; set; }
        public string MenuName { get; set; }
        public Nullable<long> PageID { get; set; }
        public string PageName { get; set; }
        public Nullable<int> parentID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> MenuIndex { get; set; }
        public string MenuIcon { get; set; }
    }
}
