//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wempe
{
    using System;
    using System.Collections.Generic;
    
    public partial class wmpMVCAuthenticationRight
    {
        public int ActionID { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string RightFor { get; set; }
        public string role { get; set; }
        public string OtherFunctions { get; set; }
        public Nullable<long> UpdateBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<bool> OnlyForCompanyUsers { get; set; }
        public Nullable<bool> ShowInMenu { get; set; }
        public string MenuText { get; set; }
        public string Id { get; set; }
        public string cssClass { get; set; }
        public Nullable<int> MenuIndex { get; set; }
        public Nullable<int> ParentId { get; set; }
    }
}
