//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wempe
{
    using System;
    using System.Collections.Generic;
    
    public partial class wmpMailBox
    {
        public long MessageNumber { get; set; }
        public string MessageId { get; set; }
        public string FromAddress { get; set; }
        public string DisplayName { get; set; }
        public string Subject { get; set; }
        public string MessageBody { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<long> OwnerID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<bool> HaveAttachment { get; set; }
    }
}
