//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wempe
{
    using System;
    using System.Collections.Generic;
    
    public partial class wmpPrintSetting
    {
        public long SettingID { get; set; }
        public Nullable<decimal> PaperTopMargin { get; set; }
        public Nullable<decimal> PaperRightMargin { get; set; }
        public Nullable<decimal> PaperBottomMargin { get; set; }
        public Nullable<decimal> PaperLeftMargin { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<long> UpdateBy { get; set; }
        public Nullable<long> OwnerID { get; set; }
    
        public virtual wmpPrintSetting wmpPrintSetting1 { get; set; }
        public virtual wmpPrintSetting wmpPrintSetting2 { get; set; }
    }
}
