//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wempe
{
    using System;
    using System.Collections.Generic;
    
    public partial class wmpRepairStatusLog
    {
        public long LogId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string RepairNumber { get; set; }
        public string Zipcode { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string Type { get; set; }
        public string IPAddress { get; set; }
    }
}
