//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wempe
{
    using System;
    using System.Collections.Generic;
    
    public partial class wmpSupplier
    {
        public long Id { get; set; }
        public string name { get; set; }
        public string mainCompany { get; set; }
        public string mainAddressLine1 { get; set; }
        public string mainAddressLine2 { get; set; }
        public string mainCity { get; set; }
        public string mainState { get; set; }
        public string mainZipCode { get; set; }
        public string mainZipCodePlusFour { get; set; }
        public string mainCountry { get; set; }
        public string mainTelephoneSegment1 { get; set; }
        public string mainTelephoneSegment2 { get; set; }
        public string mainTelephoneSegment3 { get; set; }
        public string mainTelephoneExtension { get; set; }
        public string mainFaxSegment1 { get; set; }
        public string mainFaxSegment2 { get; set; }
        public string mainFaxSegment3 { get; set; }
        public string mainEMailAddress { get; set; }
        public string mainStickerCode { get; set; }
        public string mainWempeAccount { get; set; }
        public string mainContact { get; set; }
        public string mainContactTelephoneSegment1 { get; set; }
        public string mainContactTelephoneSegment2 { get; set; }
        public string mainContactTelephoneSegment3 { get; set; }
        public string mainContactTelephoneExtension { get; set; }
        public string mainContactFaxSegment1 { get; set; }
        public string mainContactFaxSegment2 { get; set; }
        public string mainContactFaxSegment3 { get; set; }
        public string mainContactEMailAddress { get; set; }
        public string sparePartsCompany { get; set; }
        public string sparePartsAddressLine1 { get; set; }
        public string sparePartsAddressLine2 { get; set; }
        public string sparePartsCity { get; set; }
        public string sparePartsState { get; set; }
        public string sparePartsZipCode { get; set; }
        public string sparePartsZipCodePlusFour { get; set; }
        public string sparePartsCountry { get; set; }
        public string sparePartsTelephoneSegment1 { get; set; }
        public string sparePartsTelephoneSegment2 { get; set; }
        public string sparePartsTelephoneSegment3 { get; set; }
        public string sparePartsTelephoneExtension { get; set; }
        public string sparePartsFaxSegment1 { get; set; }
        public string sparePartsFaxSegment2 { get; set; }
        public string sparePartsFaxSegment3 { get; set; }
        public string sparePartsEMailAddress { get; set; }
        public string sparePartsStickerCode { get; set; }
        public string sparePartsWempeAccount { get; set; }
        public string sparePartsContact { get; set; }
        public string sparePartsContactTelephoneSegment1 { get; set; }
        public string sparePartsContactTelephoneSegment2 { get; set; }
        public string sparePartsContactTelephoneSegment3 { get; set; }
        public string sparePartsContactTelephoneExtension { get; set; }
        public string sparePartsContactFaxSegment1 { get; set; }
        public string sparePartsContactFaxSegment2 { get; set; }
        public string sparePartsContactFaxSegment3 { get; set; }
        public string sparePartsContactEMailAddress { get; set; }
        public string strapCompany { get; set; }
        public string strapAddressLine1 { get; set; }
        public string strapAddressLine2 { get; set; }
        public string strapCity { get; set; }
        public string strapState { get; set; }
        public string strapZipCode { get; set; }
        public string strapZipCodePlusFour { get; set; }
        public string strapCountry { get; set; }
        public string strapTelephoneSegment1 { get; set; }
        public string strapTelephoneSegment2 { get; set; }
        public string strapTelephoneSegment3 { get; set; }
        public string strapTelephoneExtension { get; set; }
        public string strapFaxSegment1 { get; set; }
        public string strapFaxSegment2 { get; set; }
        public string strapFaxSegment3 { get; set; }
        public string strapEMailAddress { get; set; }
        public string strapStickerCode { get; set; }
        public string strapWempeAccount { get; set; }
        public string strapContact { get; set; }
        public string strapContactTelephoneSegment1 { get; set; }
        public string strapContactTelephoneSegment2 { get; set; }
        public string strapContactTelephoneSegment3 { get; set; }
        public string strapContactTelephoneExtension { get; set; }
        public string strapContactFaxSegment1 { get; set; }
        public string strapContactFaxSegment2 { get; set; }
        public string strapContactFaxSegment3 { get; set; }
        public string strapContactEMailAddress { get; set; }
        public string billingCompany { get; set; }
        public string billingAddressLine1 { get; set; }
        public string billingAddressLine2 { get; set; }
        public string billingCity { get; set; }
        public string billingState { get; set; }
        public string billingZipCode { get; set; }
        public string billingZipCodePlusFour { get; set; }
        public string billingCountry { get; set; }
        public string billingTelephoneSegment1 { get; set; }
        public string billingTelephoneSegment2 { get; set; }
        public string billingTelephoneSegment3 { get; set; }
        public string billingTelephoneExtension { get; set; }
        public string billingFaxSegment1 { get; set; }
        public string billingFaxSegment2 { get; set; }
        public string billingFaxSegment3 { get; set; }
        public string billingEMailAddress { get; set; }
        public string billingStickerCode { get; set; }
        public string billingWempeAccount { get; set; }
        public string billingContact { get; set; }
        public string billingContactTelephoneSegment1 { get; set; }
        public string billingContactTelephoneSegment2 { get; set; }
        public string billingContactTelephoneSegment3 { get; set; }
        public string billingContactTelephoneExtension { get; set; }
        public string billingContactFaxSegment1 { get; set; }
        public string billingContactFaxSegment2 { get; set; }
        public string billingContactFaxSegment3 { get; set; }
        public string billingContactEMailAddress { get; set; }
        public string notes { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<long> UpdateBy { get; set; }
        public Nullable<long> OwnerID { get; set; }
    }
}
