//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wempe
{
    using System;
    using System.Collections.Generic;
    
    public partial class wmpSystem
    {
        public long Id { get; set; }
        public string mailHost { get; set; }
        public string mailUsername { get; set; }
        public string mailPassword { get; set; }
        public string mailFrom { get; set; }
        public string mailFromName { get; set; }
    }
}
