//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wempe
{
    using System;
    using System.Collections.Generic;
    
    public partial class wmpStoreInformation
    {
        public long Id { get; set; }
        public string storeNumber { get; set; }
        public string name { get; set; }
        public string addressLine1 { get; set; }
        public string addressLine2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zipCode { get; set; }
        public string country { get; set; }
        public string telephoneSegment1 { get; set; }
        public string telephoneSegment2 { get; set; }
        public string telephoneSegment3 { get; set; }
        public string telephoneExtension { get; set; }
        public string faxSegment1 { get; set; }
        public string faxSegment2 { get; set; }
        public string faxSegment3 { get; set; }
        public string eMailAddress { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<long> UpdateBy { get; set; }
        public Nullable<long> OwnerID { get; set; }
    }
}
