//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wempe
{
    using System;
    using System.Collections.Generic;
    
    public partial class wmpWebsitePage
    {
        public long PageID { get; set; }
        public string PageName { get; set; }
        public string PageTitle { get; set; }
        public string shortdescription { get; set; }
        public string description { get; set; }
        public string metakeywords { get; set; }
        public string metadescription { get; set; }
        public string headerstylescss { get; set; }
        public string footerjavascript { get; set; }
        public string PageImage { get; set; }
        public string PageUrl { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    }
}
